"""Emit shell configuration (.bashrc.d/ccpm.sh) from compiled profile."""

from __future__ import annotations

from pathlib import Path
from typing import Any


def emit_shell(entries: list[dict[str, Any]], output_dir: Path) -> Path | None:
    """Write shell config to output_dir/.bashrc.d/ccpm.sh.

    Processes the chain of shell entries with their strategies
    (append/replace, like claude_md). Returns the path written, or None.
    """
    if not entries:
        return None

    result = ""
    for entry in entries:
        content = _resolve_content(entry)
        if not content:
            continue

        strategy = entry.get("strategy", "append")
        if strategy == "replace":
            result = content
        elif strategy == "prepend":
            result = content + ("\n\n" if result else "") + result
        else:  # append
            result = result + ("\n\n" if result else "") + content

    if not result:
        return None

    # Add a header
    output = "#!/bin/bash\n"
    output += "# Generated by ccpm - Claude Code Profile Manager\n"
    output += "# Source this file: source ~/.bashrc.d/ccpm.sh\n\n"
    output += result.rstrip() + "\n"

    dest = output_dir / ".bashrc.d" / "ccpm.sh"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(output)
    return dest


def _resolve_content(entry: dict[str, Any]) -> str:
    """Get content from inline string or file reference."""
    if "content" in entry and entry["content"]:
        return entry["content"].strip()
    if "file" in entry and entry["file"]:
        path = Path(entry["file"])
        if not path.is_file():
            raise FileNotFoundError(
                f"Shell config file not found: {path}\n"
                f"  Hint: Check that the path exists and env vars resolved correctly"
            )
        return path.read_text().strip()
    return ""
