"""Deploy compiled profile to Docker containers."""

from __future__ import annotations

import subprocess
import tempfile
from pathlib import Path

from ccpm.core.compiler import CompiledProfile
from ccpm.emit import emit_all


def deploy_docker(
    compiled: CompiledProfile,
    container: str,
    target_path: str = "/root",
    dry_run: bool = False,
) -> list[Path]:
    """Deploy a compiled profile into a running Docker container via docker cp."""
    staging = Path(tempfile.mkdtemp(prefix="ccpm-docker-"))
    written = emit_all(compiled, staging)

    if dry_run:
        return written

    for path in written:
        rel = path.relative_to(staging)
        dest = f"{target_path}/{rel}"
        # Ensure parent dir exists in container
        parent = str(Path(dest).parent)
        subprocess.run(
            ["docker", "exec", container, "mkdir", "-p", parent],
            check=True,
            capture_output=True,
        )
        subprocess.run(
            ["docker", "cp", str(path), f"{container}:{dest}"],
            check=True,
            capture_output=True,
        )

    return written


def generate_dockerfile_snippet(compiled: CompiledProfile) -> str:
    """Generate a Dockerfile snippet that copies profile files into an image."""
    staging = Path(tempfile.mkdtemp(prefix="ccpm-dockerfile-"))
    written = emit_all(compiled, staging)

    lines = [
        f"# Generated by ccpm - Claude Code Profile Manager",
        f"# Staging dir: {staging}",
    ]
    for path in written:
        rel = path.relative_to(staging)
        lines.append(f"COPY {rel} /root/{rel}")

    return "\n".join(lines)
